### ISSUE TITLE
Is this avaiable in Moodle plugins directory?

### ISSUE THREAD

**Issue by dinism** [moodleou/moodle-quiz_answersheets#22]
This is GREAT!

**Comment by timhunt** [comment]
I submitted it yesterday. It is somewhere in here: https://moodle.org/plugins/queue.php. So, it will get published eventually. I will close this now, because there is nothing to do except wait.

You can watch https://tracker.moodle.org/browse/CONTRIB-8144 to be notified when there is progress.
