### ISSUE TITLE
A4 size in the @media print CSS

### ISSUE THREAD

**Issue by mudrd8mz** [moodleou/moodle-quiz_answersheets#25]
I haven't actually tried and tested myself. But I have a suspicion that the current CSS

```
@media print {
    /* Set the page to A4 size to prevent border lost. */
    body:not(.gecko) {
        height: 297mm;
        width: 210mm;
    }
```

will effectively affect all places in Moodle. I assume it is not a problem, just thinking about countries (such as US or Canada) that commonly use different paper sizes?

**Comment by timhunt** [comment]
Good catch!

**Comment by timhunt** [comment]
OU internal defect number: 403999

**Comment by timhunt** [comment]
The fix for this version is now pushed.
