### ISSUE TITLE
Proposal: Add setting in order to show/hide "Download review sheets in bulk"

### ISSUE THREAD

**Issue by juaneladio** [moodleou/moodle-quiz_answersheets#27]
Hi, I like this plugin, but because the option "Download review sheets in bulk" requires a set of complex instructions (and a dependency in an external tool), the plugin can have a new setting, in order to show/hide that link.

**Comment by timhunt** [comment]
There is already a way to control who can see that link. There is a capability https://github.com/moodleou/moodle-quiz_answersheets/blob/master/db/access.php#L69. You can alter the role definitions in your Moodle site to control who sees the link.
