### ISSUE TITLE
Additional information on sheet

### ISSUE THREAD

**Issue by OgreTransporter** [moodleou/moodle-quiz_answersheets#29]
It would be helpful if you could also select the login name in the information displayed in the table and the report. In our case, this is the matriculation number, which is useful for assigning students.

**Comment by timhunt** [comment]
The fields that you can select in this report should include all the ones you have selected in the admin setting 'Show user identity'. If username is important to you, you should enable it there.

**Comment by OgreTransporter** [comment]
Thank you very much! The setting is well hidden but works great! Exactly what I was looking for.
