### ISSUE TITLE
Issue related to Create attempt

### ISSUE THREAD

**Issue by HuongNV13** [moodleou/moodle-quiz_answersheets#9]
We found 2 issues related to Create Attempt:
 - Create attempt will not work if the Quiz Max Attempt set to unlimited
 - Create attempt will not work with Moodle master branch (3.8) because the code is using a deprecated function from 3.4 and it will be removed on 3.8
Please refer:
https://github.com/moodleou/moodle-quiz_answersheets/blob/6f081da7b13731b117d3d7fd427af13f34c38cc1/amd/src/create_attempt_dialog.js#L46
Need to change from ModalEvents.yes to ModalEvents.save

**Comment by timhunt** [comment]
This is done, so closing.
